// generated by directives_generate.go; DO NOT EDIT

package dnsserver

// Directives are registered in the order they should be
// executed.
//
// Ordering is VERY important. Every plugin will
// feel the effects of all other plugin below
// (after) them during a request, but they must not
// care what plugin above them are doing.
var Directives = []string{
	"root",
	"metadata",
	"cancel",
	"tls",
	"proxyproto",
	"quic",
	"https",
	"https3",
	"timeouts",
	"multisocket",
	"reload",
	"nsid",
	"bufsize",
	"bind",
	"debug",
	"trace",
	"ready",
	"health",
	"pprof",
	"prometheus",
	"errors",
	"log",
	"dnstap",
	"local",
	"dns64",
	"any",
	"loadbalance",
	"tsig",
	"cache",
	"rewrite",
	"acl",
	"header",
	"dnssec",
	"autopath",
	"minimal",
	"template",
	"transfer",
	"hosts",
	"file",
	"auto",
	"secondary",
	"loop",
	"blocklist",
	"forward",
	"erratic",
	"whoami",
	"on",
	"sign",
	"view",
}
